### ISSUE TITLE
Installed Spanish version

### ISSUE THREAD

**Issue by Westlake-1** [HynoTech/dropbox-folder-share#14]
I downloaded the plugin from WordPress and installed it automatically, but every word of the install except the plugin name were in Spanish. I deleted it then installed it again with the same result.

**Comment by AntonySalas** [comment]
The language depends on the wordpress configuration, by default the initial
language is Spanish

**Comment by Westlake-1** [comment]
AAAAH, my site was set to Canadian English and it worked when I changed to US English
