### ISSUE TITLE
sharing folder between two computer

### ISSUE THREAD

**Issue by abeerx26** [HynoTech/dropbox-folder-share#30]
Is there a way to share same folder in two different computers without any internet sharing. 
to clarify: 
computer A have archive folder that I add and edit files. I want to have the same folder in computer B and whenever I add or edit files to computer A, computer B will update the archive folder so in both computer will have same folder. IS it clear? :))

**Comment by AntonySalas** [comment]
https://www.goodsync.com/personal

Quizá pueda ayudarte ese software.
